# referenciais/marcas_conhecidas.py


MARCAS_KNOWN = [
    "MTA",
    "Le Creuset",
    "Ceraflame",
    "Rochedo",
    "Multilaser",
    "123 UTIL",
    "123UTIL",
    "3M",
    "AKORA",
    "ALLMIX",
    "krystalmix",
    "ARTHI",
    "BEMOL",
    "BETTANIN",
    "BRILHOS",
    "BRINOX",
    "CAMESA",
    "CARREFOUR",
    "CASA AMBIENTE",
    "CASA LINDA",
    "CASALINDA",
    "CASAMBIENTE",
    "CELESTE",
    "CENSOSSUD",
    "CERAFLAME",
    "CLINK",
    "COLORSTONE",
    "CONCEPT HAUS",
    "CONCEPTHAUS",
    "CONDOR",
    "DAY HOME",
    "DAYHOME",
    "DI SOLLE",
    "DIITALIA",
    "DISOLLE",
    "DOLCE HOME",
    "DOLCEHOME",
    "EKKO",
    "EIRILAR"
    "ELECTROLUX",
    "EMBRAST",
    "ETILUX",
    "EURO",
    "EURO HOME",
    "EUROHOME",
    "EUROQUADROS",
    "FLASH LIMP",
    "FLASHLIMP",
    "FRATELLI",
    "FRATTELI",
    "FRIGIGOLD",
    "FULL FIT",
    "FULLFIT",
    "HAUSKRAFT",
    "HAVAM",
    "HAVAN",
    "INGA",
    "INGÁ",
    "INOVEM",
    "KE HOME",
    "KEHOME",
    "KENYA",
    "KERS",
    "KIAN",
    "KONTUZ",
    "KUMBER",
    "LECRUSISET",
    "LEHAVI",
    "LYOR",
    "MACASSAB",
    "MAXWELL"
    "MARPAL",
    "MCASSABE",
    "MIMO",
    "MIMO STYLE",
    "MOOD",
    "MOR",
    "MOSKADA",
    "MTA",
    "MULFATTO",
    "MULTIFON",
    "NA WEB UTILIDADES",
    "NEOFLAM",
    "NEOFLAN",
    "NIAZITEX",
    "NOBRE",
    "OIKOS",
    "ORDENE",
    "ORIGINAL GLASS",
    "ORIGINAL LINE",
    "OSTER",
    "OU",
    "Ou",
    "OXFORD",
    "OXFORDS",
    "PANELUX",
    "PARAMOUNT",
    "PASSERINI",
    "PERFECT PRO",
    "PERFECTPRO",
    "PHILCO",
    "POLI SHOP",
    "POLISHOP",
    "POWER MAID",
    "POWERMAID",
    "RAYCO",
    "REDSILVER",
    "ROCHEDO",
    "ROJEMAC",
    "RUVOLO",
    "SAK'ES",
    "SCOTH BRITE",
    "SCOTHBRITE",
    "SENSEA",
    "SIGMA",
    "SIMPLO",
    "SUNGUIDER",
    "SUPERPRO",
    "T.T.S",
    "TANIA BULHOES",
    "TEFAL",
    "TOP RIO",
    "TRAMONTINA",
    "TTS",
    "TUD",
    "TUUT",
    "THOM HOME",
    "THOMHOME",
    "UNY GIFT",
    "VONDER",
    "VONNIX",
    "WAP",
    "WEEL MIX",
    "WELLMIX",
    "WMB",
    "WOLF",
    "WOLFF",
    "WYNCE",
    "YANGZI",
    "ZAFFARI",
    "ZARA",
    "ZIELOC",
    "ZYLISS",
    "ZYLLISS",
]
